name: project3_wine_weather
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.2
  - numpy=2.0.2
  - scikit-learn=1.5.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - pip
  - pip:
      - meteostat==1.6.8
